//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectFClean.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public int TransId { get; set; }
        public int ReceiveId { get; set; }
        public string Note { get; set; }
        public int Transaction_Money { get; set; }
        public System.DateTime DateTime { get; set; }
        public int SenderId { get; set; }
    }
}
